name: administrator
version: '1.0'
main: com.noinsts.administrator.Main
api-version: '1.19'
commands:
  getcoords:
    description: Показує координати відправника або іншого гравця
    usage: /getcoord [player]
  backdeath:
    description: Телепортує гравця до точки смерті.
    usage: /backdeath [player]